# stage 1
FROM node:16

RUN mkdir /app
WORKDIR /app

COPY ./.env.production ./.env.production
COPY ./package.prod.json ./package.json
COPY ./yarn.lock .
COPY ./public /app/public
COPY ./src /app/src

RUN yarn install && yarn build

# stage 2
FROM nginx:alpine

# load site config
COPY ./nginx.default.conf /etc/nginx/conf.d/default.conf

# copy the static site from the last step
COPY --from=0 /app/build /usr/share/nginx/html