version: '3'
services:
  frontend:
    container_name: todo-frontend-prod
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    expose:
      - 80


  backend:
    container_name: todo-backend-prod
    build:
      context: .
      dockerfile: ./backend/Dockerfile.prod
    expose:
      - 8000

  db:
    container_name: todo-db
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    expose:
      - ${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DB}
      DB_PORT: ${DB_PORT}

  proxy:
    image: nginx:latest
    container_name: todo-proxy-prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  db_data: